#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yamazaki Iori s22C1132PS@s.chibakoudai.jp
# SPDX-Licence-Identifier: BSD-3-Clause

import sys

ans1 = 0

for line in sys.stdin:

    try:
        ans1 += int(line)

    except:
        ans1 += float(line)

print(ans1)
